In [1]:
import numpy as np

In [2]:
a = np.arange(1, 11)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a[a > 4]

array([ 5,  6,  7,  8,  9, 10])

In [5]:
a[a <= 3]

array([1, 2, 3])

In [6]:
arr = np.arange(10)

In [7]:
len(a)

10

In [8]:
len(arr)

10

In [9]:
arr + a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
arr * a

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [11]:
arr - a

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [12]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
a / arr

C:\Users\Amir\AppData\Local\Temp\ipykernel_17504\90422887.py:1: RuntimeWarning: divide by zero encountered in divide
  a / arr


array([       inf, 2.        , 1.5       , 1.33333333, 1.25      ,
       1.2       , 1.16666667, 1.14285714, 1.125     , 1.11111111])

In [14]:
arr / arr

C:\Users\Amir\AppData\Local\Temp\ipykernel_17504\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [18]:
np.log(arr)

C:\Users\Amir\AppData\Local\Temp\ipykernel_17504\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [19]:
help(np.log)

Help on ufunc:

log = <ufunc 'log'>
    log(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Natural logarithm, element-wise.
    
    The natural logarithm `log` is the inverse of the exponential function,
    so that `log(exp(x)) = x`. The natural logarithm is logarithm in base
    `e`.
    
    Parameters
    ----------
    x : array_like
        Input value.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, t

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
a.sum()

55

In [22]:
a.mean()

5.5

In [23]:
a.max()

10

In [24]:
a.min()

1

<strong>Other summary statistics include:</strong>
<pre>
arr.min() returns 0                   minimum
arr.var() returns 8.25                variance
arr.std() returns 2.8722813232690143  standard deviation
</pre>

In [25]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                  [9, 10, 11, 12]])


In [26]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [28]:
arr_2d.shape

(3, 4)

In [29]:
arr_2d.size

12

In [30]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr_2d.sum(axis=1)

array([10, 26, 42])