In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3, 4]

In [4]:
type(my_list)

list

In [5]:
my_array = np.array(my_list)

In [6]:
type(my_array)

numpy.ndarray

In [7]:
matrix_list = [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]

In [8]:
my_matrix = np.array(matrix_list)

In [9]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(2, 12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
s = (5, 5)
np.zeros(s)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((6, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# help(np.linspace)

In [16]:
np.linspace(-1, 1, 100)

array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182,
       -0.7979798 , -0.77777778, -0.75757576, -0.73737374, -0.71717172,
       -0.6969697 , -0.67676768, -0.65656566, -0.63636364, -0.61616162,
       -0.5959596 , -0.57575758, -0.55555556, -0.53535354, -0.51515152,
       -0.49494949, -0.47474747, -0.45454545, -0.43434343, -0.41414141,
       -0.39393939, -0.37373737, -0.35353535, -0.33333333, -0.31313131,
       -0.29292929, -0.27272727, -0.25252525, -0.23232323, -0.21212121,
       -0.19191919, -0.17171717, -0.15151515, -0.13131313, -0.11111111,
       -0.09090909, -0.07070707, -0.05050505, -0.03030303, -0.01010101,
        0.01010101,  0.03030303,  0.05050505,  0.07070707,  0.09090909,
        0.11111111,  0.13131313,  0.15151515,  0.17171717,  0.19191919,
        0.21212121,  0.23232323,  0.25252525,  0.27272727,  0.29292929,
        0.31313131,  0.33333333,  0.35353535,  0.37373737,  0.39

In [17]:
np.linspace(2, 3, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# Random

np.random.rand(2)

array([0.62516846, 0.04361235])

In [20]:
np.random.rand(6, 6)

array([[0.63449637, 0.93465109, 0.22822264, 0.81714762, 0.50749781,
        0.55322257],
       [0.65673307, 0.03602172, 0.2072543 , 0.71366634, 0.61522499,
        0.43658493],
       [0.13391581, 0.92234465, 0.26659691, 0.99989938, 0.76605634,
        0.18435509],
       [0.01849515, 0.2979045 , 0.55191305, 0.52243604, 0.32056327,
        0.52800132],
       [0.29611008, 0.2976073 , 0.80718767, 0.21553893, 0.44983422,
        0.55513328],
       [0.02676782, 0.86119885, 0.31613616, 0.9219918 , 0.36276555,
        0.75270563]])

In [26]:
np.random.seed(42)
np.random.randint(1, 100, 6)

array([52, 93, 15, 72, 61, 21])

In [28]:
I = np.eye(5)

In [29]:
type(I)

numpy.ndarray

In [30]:
I.shape

(5, 5)

In [31]:
# reshape
arr_1 = np.arange(25)

In [32]:
arr_1.shape

(25,)

In [33]:
arr_1.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr_1 = arr_1.reshape(5, 5)

In [35]:
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr_1.size

25

In [37]:
arr_1.reshape(3, 5)

ValueError: cannot reshape array of size 25 into shape (3,5)

In [38]:
arr_1.shape

(5, 5)

In [40]:
arr_1.reshape(-1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [41]:
arr_1.reshape(25, -1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [42]:
arr_2 = arr_1.reshape(arr_1.shape[0], -1)

In [44]:
arr_2.shape

(5, 5)

In [45]:
arr_1.ndim

2

In [46]:
arr_2.max()

24

In [47]:
arr_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr_2.min()

0

In [49]:
arr_2.mean()

12.0

In [50]:
arr_2.argmax()

24

In [51]:
arr_2.dtype

dtype('int32')

In [52]:
arr = np.arange(0 ,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[2:6]

array([2, 3, 4, 5])

## Broadcasting

In [55]:
arr[2:6] = 100

In [56]:
arr

array([  0,   1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [57]:
arr + arr

array([  0,   2, 200, 200, 200, 200,  12,  14,  16,  18,  20])

In [58]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
arr * arr

array([    0,     1, 10000, 10000, 10000, 10000,    36,    49,    64,
          81,   100])

In [60]:
1 / arr

C:\Users\Amir\AppData\Local\Temp\ipykernel_14268\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [65]:
d2_arr = np.array(([5, 10, 15],
                 [20, 25, 30],
                 [35, 40, 45]))

d2_arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
d2_arr[2, 1]

40

In [66]:
d2_arr[1]

array([20, 25, 30])

In [67]:
d2_arr[0][1]

10

In [68]:
d2_arr[0, 1]

10

In [70]:
d2_arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [71]:
d2_arr[1:, 1:]

array([[25, 30],
       [40, 45]])

In [72]:
d2_arr[1:, :2]

array([[20, 25],
       [35, 40]])

In [73]:
arr3 = np.arange(1, 11)

In [74]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Conditional Selection

In [76]:
arr3[arr3 > 4]

array([ 5,  6,  7,  8,  9, 10])

In [77]:
cond = arr3 < 3
arr3[cond]

array([1, 2])

In [78]:
cond

array([ True,  True, False, False, False, False, False, False, False,
       False])

### NumPy Operations

In [88]:
np.random.seed(42)
mat = np.random.randint(1, 20, size=(10, 7, 3))

In [89]:
mat

array([[[ 7, 15, 11],
        [ 8,  7, 19],
        [11, 11,  4],
        [ 8,  3,  2],
        [12,  6,  2],
        [ 1, 12, 12],
        [17, 10, 16]],

       [[15, 15, 19],
        [12,  3,  5],
        [19,  7,  9],
        [ 7, 18,  4],
        [14, 18,  9],
        [ 2, 15,  7],
        [12,  8, 15]],

       [[ 3, 14, 17],
        [ 4, 18,  8],
        [ 4,  2,  6],
        [10,  4, 18],
        [12,  2, 10],
        [ 4, 14, 16],
        [15,  8, 14]],

       [[ 8, 16, 13],
        [18, 15, 13],
        [ 9, 15, 13],
        [ 1,  7,  9],
        [ 1, 12,  8],
        [11, 19, 17],
        [ 8,  3,  3]],

       [[ 1,  5, 10],
        [ 7,  9,  7],
        [ 9,  8, 12],
        [ 2,  1, 16],
        [ 5,  3, 12],
        [ 8,  3,  1],
        [ 3,  5, 15]],

       [[14,  3,  1],
        [ 5, 14,  7],
        [ 9, 15, 15],
        [10, 13, 19],
        [ 7, 17,  4],
        [ 5,  7, 13],
        [15, 11,  4]],

       [[13,  7, 19],
        [ 2, 10, 13],
        [ 6, 12, 12]

## Universal Array Functions

In [90]:
np.square(mat)

array([[[ 49, 225, 121],
        [ 64,  49, 361],
        [121, 121,  16],
        [ 64,   9,   4],
        [144,  36,   4],
        [  1, 144, 144],
        [289, 100, 256]],

       [[225, 225, 361],
        [144,   9,  25],
        [361,  49,  81],
        [ 49, 324,  16],
        [196, 324,  81],
        [  4, 225,  49],
        [144,  64, 225]],

       [[  9, 196, 289],
        [ 16, 324,  64],
        [ 16,   4,  36],
        [100,  16, 324],
        [144,   4, 100],
        [ 16, 196, 256],
        [225,  64, 196]],

       [[ 64, 256, 169],
        [324, 225, 169],
        [ 81, 225, 169],
        [  1,  49,  81],
        [  1, 144,  64],
        [121, 361, 289],
        [ 64,   9,   9]],

       [[  1,  25, 100],
        [ 49,  81,  49],
        [ 81,  64, 144],
        [  4,   1, 256],
        [ 25,   9, 144],
        [ 64,   9,   1],
        [  9,  25, 225]],

       [[196,   9,   1],
        [ 25, 196,  49],
        [ 81, 225, 225],
        [100, 169, 361],
        [ 49, 2

In [91]:
mat_sqrt = np.sqrt(mat)

In [92]:
mat_sqrt.shape

(10, 7, 3)

In [93]:
n1 = mat_sqrt[:, :, 0]

In [95]:
n1.shape

(10, 7)

In [96]:
n2 = mat_sqrt[:, :, 1]

In [97]:
n2.shape

(10, 7)

In [98]:
n3 = mat_sqrt[:, :, 2]

In [99]:
n3.shape

(10, 7)

In [100]:
np.sin(mat)

array([[[ 0.6569866 ,  0.65028784, -0.99999021],
        [ 0.98935825,  0.6569866 ,  0.14987721],
        [-0.99999021, -0.99999021, -0.7568025 ],
        [ 0.98935825,  0.14112001,  0.90929743],
        [-0.53657292, -0.2794155 ,  0.90929743],
        [ 0.84147098, -0.53657292, -0.53657292],
        [-0.96139749, -0.54402111, -0.28790332]],

       [[ 0.65028784,  0.65028784,  0.14987721],
        [-0.53657292,  0.14112001, -0.95892427],
        [ 0.14987721,  0.6569866 ,  0.41211849],
        [ 0.6569866 , -0.75098725, -0.7568025 ],
        [ 0.99060736, -0.75098725,  0.41211849],
        [ 0.90929743,  0.65028784,  0.6569866 ],
        [-0.53657292,  0.98935825,  0.65028784]],

       [[ 0.14112001,  0.99060736, -0.96139749],
        [-0.7568025 , -0.75098725,  0.98935825],
        [-0.7568025 ,  0.90929743, -0.2794155 ],
        [-0.54402111, -0.7568025 , -0.75098725],
        [-0.53657292,  0.90929743, -0.54402111],
        [-0.7568025 ,  0.99060736, -0.28790332],
        [ 0.6502

In [101]:
mat_sqrt.dtype

dtype('float64')

In [102]:
n1

array([[2.64575131, 2.82842712, 3.31662479, 2.82842712, 3.46410162,
        1.        , 4.12310563],
       [3.87298335, 3.46410162, 4.35889894, 2.64575131, 3.74165739,
        1.41421356, 3.46410162],
       [1.73205081, 2.        , 2.        , 3.16227766, 3.46410162,
        2.        , 3.87298335],
       [2.82842712, 4.24264069, 3.        , 1.        , 1.        ,
        3.31662479, 2.82842712],
       [1.        , 2.64575131, 3.        , 1.41421356, 2.23606798,
        2.82842712, 1.73205081],
       [3.74165739, 2.23606798, 3.        , 3.16227766, 2.64575131,
        2.23606798, 3.87298335],
       [3.60555128, 1.41421356, 2.44948974, 3.31662479, 1.        ,
        1.73205081, 2.82842712],
       [1.        , 3.46410162, 4.12310563, 2.64575131, 4.12310563,
        4.12310563, 1.41421356],
       [1.        , 3.46410162, 3.31662479, 2.23606798, 3.31662479,
        1.        , 4.        ],
       [4.35889894, 2.64575131, 2.82842712, 2.82842712, 4.24264069,
        2.64575131, 4.1

In [104]:
n1.shape

(10, 7)

In [109]:
np.random.seed(111)
M = np.random.randint(12, size=(3, 4))

In [110]:
M

array([[4, 4, 4, 6],
       [3, 9, 2, 6],
       [2, 8, 7, 9]])

In [111]:
M.shape

(3, 4)

In [113]:
M.sum(axis=0)

array([ 9, 21, 13, 21])

In [114]:
M.sum(axis=1)

array([18, 20, 26])