In [ ]:
import numpy as np

In [1]:
# import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np













In [3]:
# !pip install numpy

In [4]:
my_list = [1, 2, 3, 4]

In [5]:
type(my_list)

list

In [6]:
my_array = np.array(my_list)

In [7]:
type(my_array)

numpy.ndarray

In [8]:
matrix_list = [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]

In [9]:
my_matrix = np.array(matrix_list)

In [10]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(2, 12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
s = (5, 5)
np.zeros(s)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((6, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# help(np.linspace)

In [18]:
np.linspace(-1, 1, 100)

array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182,
       -0.7979798 , -0.77777778, -0.75757576, -0.73737374, -0.71717172,
       -0.6969697 , -0.67676768, -0.65656566, -0.63636364, -0.61616162,
       -0.5959596 , -0.57575758, -0.55555556, -0.53535354, -0.51515152,
       -0.49494949, -0.47474747, -0.45454545, -0.43434343, -0.41414141,
       -0.39393939, -0.37373737, -0.35353535, -0.33333333, -0.31313131,
       -0.29292929, -0.27272727, -0.25252525, -0.23232323, -0.21212121,
       -0.19191919, -0.17171717, -0.15151515, -0.13131313, -0.11111111,
       -0.09090909, -0.07070707, -0.05050505, -0.03030303, -0.01010101,
        0.01010101,  0.03030303,  0.05050505,  0.07070707,  0.09090909,
        0.11111111,  0.13131313,  0.15151515,  0.17171717,  0.19191919,
        0.21212121,  0.23232323,  0.25252525,  0.27272727,  0.29292929,
        0.31313131,  0.33333333,  0.35353535,  0.37373737,  0.39

In [19]:
np.linspace(2, 3, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# Random

np.random.rand(2)

array([0.45119931, 0.99008128])

In [25]:
np.random.rand(6, 6)

array([[3.66810832e-01, 6.48523985e-01, 2.59899126e-02, 9.58406932e-01,
        4.47149183e-01, 8.51128180e-01],
       [7.11317386e-01, 3.44994314e-06, 6.42635971e-01, 4.20507596e-01,
        8.20879533e-01, 6.17001452e-01],
       [7.36120010e-01, 3.28480368e-01, 5.16698765e-01, 2.58649384e-01,
        3.78380235e-01, 9.20847299e-01],
       [6.92587025e-01, 5.73070876e-01, 3.66546288e-03, 6.82144164e-01,
        3.09557341e-01, 7.22729500e-01],
       [1.38531426e-01, 3.14124518e-01, 9.22417616e-01, 9.57337520e-01,
        4.08819081e-01, 5.03758209e-01],
       [3.83612838e-01, 9.72658205e-01, 7.36685716e-01, 4.27555610e-02,
        7.71896671e-01, 5.97632175e-01]])

In [35]:
np.random.seed(42)
np.random.randint(1, 100, 6)

array([52, 93, 15, 72, 61, 21], dtype=int32)

In [36]:
I = np.eye(5)

In [37]:
type(I)

numpy.ndarray

In [38]:
I.shape

(5, 5)

In [39]:
# reshape
arr_1 = np.arange(25)

In [41]:
arr_1.shape

(25,)

In [42]:
arr_1.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr_1 = arr_1.reshape(5, 5)

In [46]:
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr_1.reshape(3, 5)

ValueError: cannot reshape array of size 25 into shape (3,5)

In [48]:
type(2)

int